name: .NET Core

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
  
  test:
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Test dotnet
        run: dotnet test
  
  deploy:
    needs: [test]
    runs-on: [ubuntu-latest]
    steps:
      - name: dotnet publish
        run: |
          dotnet publish -c Release -o Scrobblebot 
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: Scrobblebot # Replace with your app name
          publish-profile: $ # Define secret variable in repository settings as per action documentation
          package: './dotnetcorewebapp' 
